version: '3'
services:
  postgresql:
    image: postgres
    container_name: nest-lesson-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: nest-lesson
      POSTGRES_PASSWORD: nest-lesson
      POSTGRES_DATABASE: postgres
      POSTGRES_HOST: localhost
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-lesson
    ports:
      - '6379:6379'
